services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_USERNAME="elastic"
      - ELASTIC_PASSWORD="elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: kibana:8.8.1
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME="elastic"
      - ELASTIC_PASSWORD="elastic"